# Generated by Django 3.2.6 on 2022-06-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
    ]
